# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 8

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 23

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 10

# Offense count: 1
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
    - '**/spec/requests/**/*'
    - '**/spec/routing/**/*'
    - '**/spec/system/**/*'
    - '**/spec/views/**/*'
    - 'spec/acceptance/init_spec.rb'

# Offense count: 2
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 12

# Offense count: 2
RSpec/MultipleExpectations:
  Max: 9
